dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
     - libboost-test-dev
     - libboost-filesystem-dev
     - libboost-program-options-dev
     #- python3-pip
#    - libboost-all-dev # it works

# for tech commit
script:
#- pip install --user conan
- pwd
- ls
- mkdir build
- cd build
- ./build-boost.sh
#- conan install ..
- cmake ..
- cmake --build .
- cmake --build . --target tests
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulinkfly:$BINTRAY_API_KEY "https://api.bintray.com/content/linkfly/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
