dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
#     - libboost-test-dev
#     - libboost-filesystem-dev
#     - libboost-program-options-dev
     #- python3-pip
#    - libboost-all-dev # it works

# for tech commit
script:
#- pip install --user conan
- pwd
- ls
- mkdir build
- cd build
- export boost_version=1_72_0
- export boost_ptversion=1.72.0
- export boost_factory_rel="boost_factory"
- export boost_factory="$(pwd)/$boost_factory_rel"
- export boost_prefix_rel="$boost_factory_rel/usr/lib/boost_$boost_version"
- export boost_prefix="$(pwd)/$boost_prefix_rel"
- echo "[INFO] boost_factory = $boost_factory"
- echo "[INFO] boost_prefix = $boost_prefix"
- echo "[INFO] boost_version = $boost_version"
- echo "[INFO] boost_ptversion = $boost_ptversion"
- ../build-boost.sh "$boost_factory" "$boost_prefix" "$boost_version" "$boost_ptversion"
#- conan install ..
- export BOOST_ROOT="$boost_prefix"
- export boost_librarydir_rel="$boost_prefix_rel/lib"
- export BOOST_LIBRARYDIR="$(pwd)/$boost_librarydir_rel"
- export BOOST_INCLUDEDIR="$boost_prefix/include"
- echo "[INFO] BOOST_ROOT = $BOOST_ROOT"
- echo "[INFO] BOOST_LIBRARYDIR = $BOOST_LIBRARYDIR"
- echo "[INFO] BOOST_INCLUDEDIR = $BOOST_INCLUDEDIR"
- cmake ..
- cmake --build .
- cmake --build . --target tests
- echo "[INFO] $boost_librarydir_rel = $boost_librarydir_rel"
- ../prepare-config "$boost_librarydir_rel" "$(pwd)"
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulinkfly:$BINTRAY_API_KEY "https://api.bintray.com/content/linkfly/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/bayan-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
