#!/bin/bash

LD_LIBRARY_PATH="$1"
save_dir="$2"

wrapTo() {
main=$1
wrapped=$2
echo "LD_LIBRARY_PATH="$LD_LIBRARY_PATH"">"$save_dir/$main-config.conf"
echo "[INFO] Checking saved config: "$save_dir/$main-config.conf""

mainfile="$save_dir/$main"
wrappedfile="$save_dir/$wrapped"

mv "$mainfile" "$wrappedfile"
echo "[INFO] Wrapper file: "$mainfile""
echo "[INFO] Wrapped file: "$wrappedfile""

echo "cd $(dirname "$0">"$mainfile"
echo ". $main-config.conf">>"$mainfile"
echo "echo "$LD_LIBRARY_PATH"">>"$mainfile"
echo "LD_LIBRARY_PATH="$LD_LIBRARY_PATH" ./$wrapped \$*">>"$mainfile"

echo "[INFO] Checking saved wrapper: $(ls "$mainfile")"
echo "[INFO] Checking saved wrapped: $(ls "$wrappedfile")"

chmod u+x "$mainfile"
chmod u+x "$wrappedfile"
}

wrapTo tests tests-orig
wrapTo bayan bayan-orig
